# Generated by Django 2.1.5 on 2019-01-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='imagen',
            new_name='imagene',
        ),
    ]
