# Generated by Django 2.1.5 on 2019-01-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0002_auto_20190110_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
    ]
