# Generated by Django 2.1.5 on 2019-01-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0003_remove_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='descripcion',
            field=models.TextField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
