# Generated by Django 2.1.5 on 2019-01-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0005_perfil_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='centros',
            name='ubicacion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
