# Generated by Django 2.1.5 on 2019-01-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0007_centros_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='correo',
            new_name='email',
        ),
    ]
