# Generated by Django 2.1.5 on 2019-01-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0008_auto_20190111_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
